# Generated by Django 4.0.2 on 2022-02-12 08:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('service', models.CharField(choices=[('Пакет Базовый подбор', 'Пакет Базовый подбор'), ('Пакет Подбор Плюс', 'Пакет Подбор Плюс'), ('Пакет Все включено', 'Пакет Все включено')], max_length=20, verbose_name='Услуга')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения формы')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('-application_date', 'name'),
            },
        ),
    ]
