# Generated by Django 4.0.2 on 2022-02-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('черновик', 'Чeрновик'), ('опубликовано', 'Опубликовано')], default='черновик', max_length=12, verbose_name='Статус поста'),
        ),
    ]
